languageCode = "en-us"
title = "Dreamgrove"
copyright = "Dreamgrove"
theme = "dg-theme"
enableGitInfo = true

[blackfriday]
  hrefTargetBlank = true
  
[markup.goldmark.renderer]
  unsafe= true

[params]
  enableElune = true
  description = "Dreamgrove is the home of all things Druid. Guides, articles, theorycrafting, and more!"
  restoExternalURL = "http://questionablyepic.com"
  currentPatch = "9.0"
  pastPatches = "7.3.5,8.0,8.1,8.2,8.3"

[taxonomies]
  series = "series"
